-- Bonusvraag 1 (Topscorer) en 2 (Beste speler): voeg spelerslijsten toe als dropdown
-- en update de subtitle tekst

UPDATE public.bonus_questions
SET
  answer_type    = 'options',
  description    = 'Indien jouw gewenste selectie niet in de lijst voorkomt, stuur dan een bericht naar de organisatie.',
  answer_options = ARRAY[
    'Julián Álvarez',
    'Lautaro Martínez',
    'Lionel Messi',
    'Kevin de Bruyne',
    'Romelu Lukaku',
    'Igor Thiago',
    'Matheus Cunha',
    'Raphinha',
    'Vinícius Júnior',
    'Luis Díaz',
    'Luis Javier Suárez',
    'Florian Wirtz',
    'Jamal Musiala',
    'Kai Havertz',
    'Enner Valencia',
    'Mohamed Salah',
    'Bukayo Saka',
    'Harry Kane',
    'Jude Bellingham',
    'Ollie Watkins',
    'Désire Doué',
    'Kylian Mbappé',
    'Michael Olise',
    'Ousmane Dembélé',
    'Antoine Semenyo',
    'Ayase Ueda',
    'Andrej Kramaric',
    'Brahim Díaz',
    'Raúl Jiménez',
    'Cody Gakpo',
    'Donyell Malen',
    'Memphis Depay',
    'Erling Haaland',
    'Bruno Fernandes',
    'Cristiano Ronaldo',
    'Gonçalo Ramos',
    'Scott McTominay',
    'Sadio Mané',
    'Dani Olmo',
    'Ferran Torres',
    'Lamine Yamal',
    'Mikel Merino',
    'Mikel Oyarzabal',
    'Nico Williams',
    'Arda Güler',
    'Darwin Núñez',
    'Christian Pulisic',
    'Son Heung-Min',
    'Alexander Isak',
    'Viktor Gyökeres'
  ]
WHERE question = 'Topscorer';

UPDATE public.bonus_questions
SET
  answer_type    = 'options',
  description    = 'Indien jouw gewenste selectie niet in de lijst voorkomt, stuur dan een bericht naar de organisatie.',
  answer_options = ARRAY[
    'Alexis Mac Allister',
    'Enzo Fernández',
    'Julián Álvarez',
    'Lautaro Martínez',
    'Lionel Messi',
    'Kevin de Bruyne',
    'Matheus Cunha',
    'Neymar',
    'Raphinha',
    'Vinícius Júnior',
    'Luis Díaz',
    'Florian Wirtz',
    'Jamal Musiala',
    'Mohamed Salah',
    'Bukayo Saka',
    'Declan Rice',
    'Harry Kane',
    'Jude Bellingham',
    'Désire Doué',
    'Kylian Mbappé',
    'Michael Olise',
    'Ousmane Dembélé',
    'Luka Modric',
    'Brahim Díaz',
    'Raúl Jiménez',
    'Cody Gakpo',
    'Denzel Dumfries',
    'Donyell Malen',
    'Frenkie de Jong',
    'Memphis Depay',
    'Virgil van Dijk',
    'Erling Haaland',
    'Bruno Fernandes',
    'Cristiano Ronaldo',
    'Gonçalo Ramos',
    'João Neves',
    'Nuno Mendes',
    'Vitinha',
    'Sadio Mané',
    'Dani Olmo',
    'Ferran Torres',
    'Lamine Yamal',
    'Mikel Oyarzabal',
    'Nico Williams',
    'Pedri',
    'Rodri',
    'Arda Güler',
    'Darwin Núñez',
    'Son Heung-Min',
    'Viktor Gyökeres'
  ]
WHERE question = 'Beste speler';
