-- WK 2026 Groepsfase — correcte wedstrijdtijden (UTC) en venues
-- Tijden aangeleverd in CEST (UTC+2); omgezet naar UTC

-- ── Matchdag 1 ────────────────────────────────────────────────────────────────
UPDATE public.matches SET kickoff_at='2026-06-11T19:00:00Z', venue='Mexico City',   match_number=1  WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='México')             AND away_team_id=(SELECT id FROM public.teams WHERE name='Zuid-Afrika');
UPDATE public.matches SET kickoff_at='2026-06-12T02:00:00Z', venue='Guadalajara',   match_number=2  WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Zuid-Korea')          AND away_team_id=(SELECT id FROM public.teams WHERE name='Tsjechië');
UPDATE public.matches SET kickoff_at='2026-06-12T19:00:00Z', venue='Toronto',       match_number=3  WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Canada')              AND away_team_id=(SELECT id FROM public.teams WHERE name='Bosnië-Herzegovina');
UPDATE public.matches SET kickoff_at='2026-06-13T01:00:00Z', venue='Los Angeles',   match_number=4  WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Verenigde Staten')    AND away_team_id=(SELECT id FROM public.teams WHERE name='Paraguay');
UPDATE public.matches SET kickoff_at='2026-06-13T19:00:00Z', venue='San Francisco', match_number=5  WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Qatar')               AND away_team_id=(SELECT id FROM public.teams WHERE name='Zwitserland');
UPDATE public.matches SET kickoff_at='2026-06-13T22:00:00Z', venue='New York',      match_number=6  WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Brazilië')            AND away_team_id=(SELECT id FROM public.teams WHERE name='Marokko');
UPDATE public.matches SET kickoff_at='2026-06-14T01:00:00Z', venue='Boston',        match_number=7  WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Haïti')              AND away_team_id=(SELECT id FROM public.teams WHERE name='Schotland');
UPDATE public.matches SET kickoff_at='2026-06-14T04:00:00Z', venue='Vancouver',     match_number=8  WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Australië')           AND away_team_id=(SELECT id FROM public.teams WHERE name='Turkije');
UPDATE public.matches SET kickoff_at='2026-06-14T17:00:00Z', venue='Houston',       match_number=9  WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Duitsland')           AND away_team_id=(SELECT id FROM public.teams WHERE name='Curaçao');
UPDATE public.matches SET kickoff_at='2026-06-14T20:00:00Z', venue='Dallas',        match_number=10 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Nederland')           AND away_team_id=(SELECT id FROM public.teams WHERE name='Japan');
UPDATE public.matches SET kickoff_at='2026-06-14T23:00:00Z', venue='Philadelphia',  match_number=11 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Ivoorkust')          AND away_team_id=(SELECT id FROM public.teams WHERE name='Ecuador');
UPDATE public.matches SET kickoff_at='2026-06-15T02:00:00Z', venue='Monterrey',     match_number=12 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Zweden')             AND away_team_id=(SELECT id FROM public.teams WHERE name='Tunesië');
UPDATE public.matches SET kickoff_at='2026-06-15T16:00:00Z', venue='Atlanta',       match_number=13 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Spanje')             AND away_team_id=(SELECT id FROM public.teams WHERE name='Kaapverdië');
UPDATE public.matches SET kickoff_at='2026-06-15T19:00:00Z', venue='Seattle',       match_number=14 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='België')             AND away_team_id=(SELECT id FROM public.teams WHERE name='Egypte');
UPDATE public.matches SET kickoff_at='2026-06-15T22:00:00Z', venue='Miami',         match_number=15 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Saoedi-Arabië')      AND away_team_id=(SELECT id FROM public.teams WHERE name='Uruguay');
UPDATE public.matches SET kickoff_at='2026-06-16T01:00:00Z', venue='Los Angeles',   match_number=16 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Iran')               AND away_team_id=(SELECT id FROM public.teams WHERE name='Nieuw-Zeeland');
UPDATE public.matches SET kickoff_at='2026-06-16T19:00:00Z', venue='New York',      match_number=17 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Frankrijk')          AND away_team_id=(SELECT id FROM public.teams WHERE name='Senegal');
UPDATE public.matches SET kickoff_at='2026-06-16T22:00:00Z', venue='Boston',        match_number=18 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Irak')               AND away_team_id=(SELECT id FROM public.teams WHERE name='Noorwegen');
UPDATE public.matches SET kickoff_at='2026-06-17T01:00:00Z', venue='Kansas City',   match_number=19 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Argentinië')         AND away_team_id=(SELECT id FROM public.teams WHERE name='Algerije');
UPDATE public.matches SET kickoff_at='2026-06-17T04:00:00Z', venue='San Francisco', match_number=20 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Oostenrijk')         AND away_team_id=(SELECT id FROM public.teams WHERE name='Jordanië');
UPDATE public.matches SET kickoff_at='2026-06-17T17:00:00Z', venue='Houston',       match_number=21 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Portugal')           AND away_team_id=(SELECT id FROM public.teams WHERE name IN ('Congo-Kinshasa','DR Congo'));
UPDATE public.matches SET kickoff_at='2026-06-17T20:00:00Z', venue='Dallas',        match_number=22 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Engeland')           AND away_team_id=(SELECT id FROM public.teams WHERE name='Kroatië');
UPDATE public.matches SET kickoff_at='2026-06-17T23:00:00Z', venue='Toronto',       match_number=23 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Ghana')              AND away_team_id=(SELECT id FROM public.teams WHERE name='Panama');
UPDATE public.matches SET kickoff_at='2026-06-18T02:00:00Z', venue='Mexico City',   match_number=24 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Oezbekistan')        AND away_team_id=(SELECT id FROM public.teams WHERE name='Colombia');

-- ── Matchdag 2 ────────────────────────────────────────────────────────────────
UPDATE public.matches SET kickoff_at='2026-06-18T16:00:00Z', venue='Atlanta',       match_number=25 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Tsjechië')           AND away_team_id=(SELECT id FROM public.teams WHERE name='Zuid-Afrika');
UPDATE public.matches SET kickoff_at='2026-06-18T19:00:00Z', venue='Los Angeles',   match_number=26 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Zwitserland')        AND away_team_id=(SELECT id FROM public.teams WHERE name='Bosnië-Herzegovina');
UPDATE public.matches SET kickoff_at='2026-06-18T22:00:00Z', venue='Vancouver',     match_number=27 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Canada')             AND away_team_id=(SELECT id FROM public.teams WHERE name='Qatar');
UPDATE public.matches SET kickoff_at='2026-06-19T01:00:00Z', venue='Guadalajara',   match_number=28 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='México')             AND away_team_id=(SELECT id FROM public.teams WHERE name='Zuid-Korea');
UPDATE public.matches SET kickoff_at='2026-06-19T19:00:00Z', venue='Seattle',       match_number=29 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Verenigde Staten')   AND away_team_id=(SELECT id FROM public.teams WHERE name='Australië');
UPDATE public.matches SET kickoff_at='2026-06-19T22:00:00Z', venue='Boston',        match_number=30 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Schotland')          AND away_team_id=(SELECT id FROM public.teams WHERE name='Marokko');
UPDATE public.matches SET kickoff_at='2026-06-20T00:30:00Z', venue='Philadelphia',  match_number=31 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Brazilië')           AND away_team_id=(SELECT id FROM public.teams WHERE name='Haïti');
UPDATE public.matches SET kickoff_at='2026-06-20T03:00:00Z', venue='San Francisco', match_number=32 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Turkije')            AND away_team_id=(SELECT id FROM public.teams WHERE name='Paraguay');
UPDATE public.matches SET kickoff_at='2026-06-20T17:00:00Z', venue='Houston',       match_number=33 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Nederland')          AND away_team_id=(SELECT id FROM public.teams WHERE name='Zweden');
UPDATE public.matches SET kickoff_at='2026-06-20T20:00:00Z', venue='Toronto',       match_number=34 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Duitsland')          AND away_team_id=(SELECT id FROM public.teams WHERE name='Ivoorkust');
UPDATE public.matches SET kickoff_at='2026-06-20T23:00:00Z', venue='Kansas City',   match_number=35 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Ecuador')            AND away_team_id=(SELECT id FROM public.teams WHERE name='Curaçao');
UPDATE public.matches SET kickoff_at='2026-06-21T00:00:00Z', venue='Monterrey',     match_number=36 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Tunesië')            AND away_team_id=(SELECT id FROM public.teams WHERE name='Japan');
UPDATE public.matches SET kickoff_at='2026-06-21T16:00:00Z', venue='Atlanta',       match_number=37 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Spanje')             AND away_team_id=(SELECT id FROM public.teams WHERE name='Saoedi-Arabië');
UPDATE public.matches SET kickoff_at='2026-06-21T19:00:00Z', venue='Los Angeles',   match_number=38 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='België')             AND away_team_id=(SELECT id FROM public.teams WHERE name='Iran');
UPDATE public.matches SET kickoff_at='2026-06-21T22:00:00Z', venue='Miami',         match_number=39 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Uruguay')            AND away_team_id=(SELECT id FROM public.teams WHERE name='Kaapverdië');
UPDATE public.matches SET kickoff_at='2026-06-22T01:00:00Z', venue='Vancouver',     match_number=40 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Nieuw-Zeeland')      AND away_team_id=(SELECT id FROM public.teams WHERE name='Egypte');
UPDATE public.matches SET kickoff_at='2026-06-22T17:00:00Z', venue='Dallas',        match_number=41 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Argentinië')         AND away_team_id=(SELECT id FROM public.teams WHERE name='Oostenrijk');
UPDATE public.matches SET kickoff_at='2026-06-22T21:00:00Z', venue='Philadelphia',  match_number=42 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Frankrijk')          AND away_team_id=(SELECT id FROM public.teams WHERE name='Irak');
UPDATE public.matches SET kickoff_at='2026-06-23T00:00:00Z', venue='New York',      match_number=43 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Noorwegen')          AND away_team_id=(SELECT id FROM public.teams WHERE name='Senegal');
UPDATE public.matches SET kickoff_at='2026-06-23T03:00:00Z', venue='San Francisco', match_number=44 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Jordanië')           AND away_team_id=(SELECT id FROM public.teams WHERE name='Algerije');
UPDATE public.matches SET kickoff_at='2026-06-23T17:00:00Z', venue='Houston',       match_number=45 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Portugal')           AND away_team_id=(SELECT id FROM public.teams WHERE name='Oezbekistan');
UPDATE public.matches SET kickoff_at='2026-06-23T20:00:00Z', venue='Boston',        match_number=46 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Engeland')           AND away_team_id=(SELECT id FROM public.teams WHERE name='Ghana');
UPDATE public.matches SET kickoff_at='2026-06-23T23:00:00Z', venue='Toronto',       match_number=47 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Panama')             AND away_team_id=(SELECT id FROM public.teams WHERE name='Kroatië');
UPDATE public.matches SET kickoff_at='2026-06-24T02:00:00Z', venue='Guadalajara',   match_number=48 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Colombia')           AND away_team_id=(SELECT id FROM public.teams WHERE name IN ('Congo-Kinshasa','DR Congo'));

-- ── Matchdag 3 (gelijktijdig per groep) ──────────────────────────────────────
UPDATE public.matches SET kickoff_at='2026-06-24T19:00:00Z', venue='Vancouver',     match_number=49 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Zwitserland')        AND away_team_id=(SELECT id FROM public.teams WHERE name='Canada');
UPDATE public.matches SET kickoff_at='2026-06-24T19:00:00Z', venue='Seattle',       match_number=50 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Bosnië-Herzegovina') AND away_team_id=(SELECT id FROM public.teams WHERE name='Qatar');
UPDATE public.matches SET kickoff_at='2026-06-24T22:00:00Z', venue='Miami',         match_number=51 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Schotland')          AND away_team_id=(SELECT id FROM public.teams WHERE name='Brazilië');
UPDATE public.matches SET kickoff_at='2026-06-24T22:00:00Z', venue='Atlanta',       match_number=52 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Marokko')            AND away_team_id=(SELECT id FROM public.teams WHERE name='Haïti');
UPDATE public.matches SET kickoff_at='2026-06-25T01:00:00Z', venue='Mexico City',   match_number=53 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Tsjechië')           AND away_team_id=(SELECT id FROM public.teams WHERE name='México');
UPDATE public.matches SET kickoff_at='2026-06-25T01:00:00Z', venue='Monterrey',     match_number=54 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Zuid-Afrika')        AND away_team_id=(SELECT id FROM public.teams WHERE name='Zuid-Korea');
UPDATE public.matches SET kickoff_at='2026-06-25T20:00:00Z', venue='Philadelphia',  match_number=55 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Curaçao')            AND away_team_id=(SELECT id FROM public.teams WHERE name='Ivoorkust');
UPDATE public.matches SET kickoff_at='2026-06-25T20:00:00Z', venue='New York',      match_number=56 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Ecuador')            AND away_team_id=(SELECT id FROM public.teams WHERE name='Duitsland');
UPDATE public.matches SET kickoff_at='2026-06-25T23:00:00Z', venue='Dallas',        match_number=57 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Japan')              AND away_team_id=(SELECT id FROM public.teams WHERE name='Zweden');
UPDATE public.matches SET kickoff_at='2026-06-25T23:00:00Z', venue='Kansas City',   match_number=58 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Tunesië')            AND away_team_id=(SELECT id FROM public.teams WHERE name='Nederland');
UPDATE public.matches SET kickoff_at='2026-06-26T02:00:00Z', venue='Los Angeles',   match_number=59 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Turkije')            AND away_team_id=(SELECT id FROM public.teams WHERE name='Verenigde Staten');
UPDATE public.matches SET kickoff_at='2026-06-26T02:00:00Z', venue='San Francisco', match_number=60 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Paraguay')           AND away_team_id=(SELECT id FROM public.teams WHERE name='Australië');
UPDATE public.matches SET kickoff_at='2026-06-26T19:00:00Z', venue='Boston',        match_number=61 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Noorwegen')          AND away_team_id=(SELECT id FROM public.teams WHERE name='Frankrijk');
UPDATE public.matches SET kickoff_at='2026-06-26T19:00:00Z', venue='Toronto',       match_number=62 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Senegal')            AND away_team_id=(SELECT id FROM public.teams WHERE name='Irak');
UPDATE public.matches SET kickoff_at='2026-06-27T00:00:00Z', venue='Houston',       match_number=63 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Kaapverdië')         AND away_team_id=(SELECT id FROM public.teams WHERE name='Saoedi-Arabië');
UPDATE public.matches SET kickoff_at='2026-06-27T00:00:00Z', venue='Guadalajara',   match_number=64 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Uruguay')            AND away_team_id=(SELECT id FROM public.teams WHERE name='Spanje');
UPDATE public.matches SET kickoff_at='2026-06-27T03:00:00Z', venue='Seattle',       match_number=65 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Egypte')             AND away_team_id=(SELECT id FROM public.teams WHERE name='Iran');
UPDATE public.matches SET kickoff_at='2026-06-27T03:00:00Z', venue='Vancouver',     match_number=66 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Nieuw-Zeeland')      AND away_team_id=(SELECT id FROM public.teams WHERE name='België');
UPDATE public.matches SET kickoff_at='2026-06-27T21:00:00Z', venue='New York',      match_number=67 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Panama')             AND away_team_id=(SELECT id FROM public.teams WHERE name='Engeland');
UPDATE public.matches SET kickoff_at='2026-06-27T21:00:00Z', venue='Philadelphia',  match_number=68 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Kroatië')            AND away_team_id=(SELECT id FROM public.teams WHERE name='Ghana');
UPDATE public.matches SET kickoff_at='2026-06-27T23:30:00Z', venue='Miami',         match_number=69 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Colombia')           AND away_team_id=(SELECT id FROM public.teams WHERE name='Portugal');
UPDATE public.matches SET kickoff_at='2026-06-27T23:30:00Z', venue='Atlanta',       match_number=70 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name IN ('Congo-Kinshasa','DR Congo')) AND away_team_id=(SELECT id FROM public.teams WHERE name='Oezbekistan');
UPDATE public.matches SET kickoff_at='2026-06-28T02:00:00Z', venue='Kansas City',   match_number=71 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Algerije')           AND away_team_id=(SELECT id FROM public.teams WHERE name='Oostenrijk');
UPDATE public.matches SET kickoff_at='2026-06-28T02:00:00Z', venue='Dallas',        match_number=72 WHERE stage='group' AND home_team_id=(SELECT id FROM public.teams WHERE name='Jordanië')           AND away_team_id=(SELECT id FROM public.teams WHERE name='Argentinië');
