-- Echte naam van de deelnemer, getoond onder de gebruikersnaam in klassementen.
ALTER TABLE public.profiles
  ADD COLUMN full_name TEXT;

-- Seed o.b.v. de aangeleverde deelnemerslijst (usernames geverifieerd tegen de db)
UPDATE public.profiles SET full_name = v.full_name
FROM (VALUES
  ('Bart van Merwijk',        'Bart van Hout'),
  ('Smiley mcVince',          'Vince van Gastel'),
  ('Nikkeitim',               'Tim Hardenbol'),
  ('GJ91',                    'Geert-Jan Bernouw'),
  ('fc Prutseria',            'Wouter v/d Weg'),
  ('DeniseBernouw',           'Denise Bernouw'),
  ('Hollandsegroente',        'Mike Bouterse'),
  ('Patstradamus',            'Patrick Schmitt'),
  ('squawktheo',              'Theo Schmitt'),
  ('steveloper',              'Stefan Roobol'),
  ('Pep Stuit',               'Daniël Stuit'),
  ('Messiaankes',             'Anke Daling'),
  ('Mikey',                   'Mike van Kaam'),
  ('bobberg',                 'Bob v/d Berg'),
  ('Andre Remie',             'André Remie'),
  ('Hugovdv',                 'Hugo v/d Vlis'),
  ('CoachRonald',             'Mitchell v/d Velde'),
  ('BasU',                    'Bas Uitbeijerse'),
  ('Bonaldinho',              'Nick Boontjes'),
  ('pimp',                    'Pim van Hout'),
  ('diffadif',                'Dave van Kaam'),
  ('Oranje1',                 'Rianne de Jong'),
  ('Oranje Leeuwtje',         'Ed Stuit'),
  ('Leonidas',                'Leon Koote'),
  ('Daan',                    'Daan v/d Vlis'),
  ('Audi#8',                  'Martin Oudshoorn'),
  ('Het scheermes van Lagos', 'Wilfred Meulstee'),
  ('SBS6Robben',              'Hans Kool'),
  ('NickvanSolingen',         'Nick van Solingen'),
  ('MyNameIsJeff',            'Jaafar Quraishi'),
  ('MFP013',                  'Marcos Fernandez Posteguillo'),
  ('Kriskros',                'Chris Meijburg'),
  ('dylan',                   'Dylan van Hengel'),
  ('Randy',                   'Randy Schriek'),
  ('Ado-te-Traag',            'Paul Schlömer'),
  ('WKkneusje',               'Ferry Leer'),
  ('TessaYved',               'Tessa Schmitt'),
  ('Paolo di Camio',          'Paul van Kaam'),
  ('VV BvA',                  'Brian van Amerongen'),
  ('Dickie Puntenpakker',     'Richard van Baarlen'),
  ('AndreaF',                 'Andrea Fernandez Posteguillo'),
  ('JJHB',                    'Jeroen Hanna Boulos'),
  ('Zigzas',                  'Sascha Remie'),
  ('Baltimortje 2026',        'Ed Schmitt'),
  ('Ceciel van Persie',       'Ceciel Kip'),
  ('Swansea United',          'Mischa Zwaans'),
  ('anthhoooo',               'Anthony v/d Velde'),
  ('KaatjeMol9',              'Yvonne Schmitt'),
  ('Henkiepenkie',            'Henk Schouten'),
  ('DMeijndert',              'Daniël Meijndert'),
  ('Marleen',                 'Marleen de Waard')
) AS v(username, full_name)
WHERE public.profiles.username = v.username;
